var languageService = angular.module('languageService', []);

languageService.factory('languageService', ['getLocale',
    function languageService(getLocale) {
        return function () {
            var languagesData = [];
            languagesData['zh-cn'] = {
                yourBirthday: '请输入您的生日',
                credNotValidTips: '这是由于登入时间过长造成的，请重新登入。要重新登入，请点击"确定"， 否则点击"取消"。',
                credNotValid: '登录凭据已过期',
                UpdatePassword: '修改密码',
                AdministratorAdded: '由管理员添加',
                Created: '帐号注册于',
                CardNumber: '一卡通卡号',
                accountAndPassword: '帐号及密码',
                PersonCategoryHelp: '请选择您所属的人员类别。',
                UsernameHelpLogin: '你在这里注册的用户名/帐号。',
                PasswordHelpLogin: '该用户名/帐号所对应的密码/口令。',
                PersonCategory: '您是',
                logoutTips: '登出后，如要访问特定信息，需要重新登入。登出请点击"登出"， 否则请点击"取消"。',
                yestoLogout: '确认要登出？',
                menuLogout: '登 出',
                loginSubmit: '登 入',
                Ok: '确 定',
                Cancel: '取 消',
                ToggleMenu: '菜单开关',
                label: '昆山校区',
                brandColor: "color: #404040",
                menuAbout: '关于昆山校区',
                menuNews: '新 闻',
                menuNotices: '通 知',
                profile: '个人资料',
                User: '用  户 ',
                Username: '用户名',
                PleaseInputaUsername: '请输入一个用户名',
                Agreement: '注册条款',
                UsernameHelp: '可以包含大小写字母、数字，不能包含特殊符号, 最少 5 个字符。',
                CheckingifThisUsernameisAvailable: '检查此用户名是否可用...',
                ThisUsernameisAlreadyTaken: '此用户名已被使用。',
                UsernameContainSpecialCharactors: '用户名包含了特殊字符。',
                Password: '密  码',
                PasswordHelp: '口令密码应至少包含一个大小写字母、数字、特殊符号，最少 8 个字符。',
                PasswordisNotQualified: '口令密码未能满足要求',
                Required: '*必需的',
                usernameMinlengthError: '最少 5 个字符。',
                isOk: '没有问题',
                passwordMinlengthError: '密码最少 8 个字符。',
                Reset: '重 置',
                newuserSubmit: '注 册',
                menuLogin: '登 入',
                menuRegister: '用户注册',
                RegisteredSuccessfully: '注册成功，前往登陆页面......',
                RegisteredFailed: '注册失败，服务端问题。',
                serviceRequestFault: '服务请求失败。',
                profileMenuDropdown: '个人资料下拉菜单。',
                Category: '人员类别',
                showPassword: '显示密码',
                hidePassword: '隐藏密码',
                passportNumber: '护照号码',
                IDNumber: '身份证号',
                YourIDNumber: '您的身份证号码',
                YourPassportNumber: '您的护照号码',
                IDNumberHelp: '身份证号码是18位的数字，特殊的身份证号码为17位数字并以大写的X结尾。',
                PassportNumberHelp: '仅包含大写字母和数字，4-9 位',
                IdNumberNotQualified: '身份证号码不正确',
                PassportNumberNotQualified: '护照号码不正确。',
                NextStep: '下一步 》',
                firstName: '姓  氏',               
                lastName: '名  称',
                firstNameHelp: '姓名中的第一个或第二个汉字。应以汉字/大写字母开头，不能包含特殊符号和数字。',
                PleaseInputaFirstname: '请输入您的姓氏',
                PleaseInputaLastname: '请输入您的名字',
                NoSpecialCharactors: '不能包含特殊字符。',
                lastNameHelp: '您的名字。应以汉字/大写字母开头，不能包含特殊符号和数字。',
                PleaseSetAPassword: '请提供一个密码',
                Gender: '性  别',
                selectPersonCategory: '请选择你的组别',
                visaNumber: '签证编号',
                YourVisaNumber: '签证/居留许可/编号',
                selectGender: '请选择性别',
                Birthday: '生  日',
                selectLanguage: '选择语言',
                BadNameFormat: '错误的姓名格式。',
                BasicProfile: '基本资料',
                Fullname: '姓  名',
                mobile: '手机号码',
                PositionDepartment: '职位-部门',
                last_updated: '上次更新时间',
                passportVisa: '护照及签证信息',
                notAdded: ' - 暂 无 - ',
                workplace: '工作单位',
                passportType: '护照类别',
                visaType: '签证类别',
                passportValidDate: '护照有效期',
                visaValidDate: '签证有效期',
                physicalCondition: '个人体征',
                Height: '身  高',
                Weight: '体  重',
                Shoesize: '鞋  码',
                careerInfo: '职业信息',
                Position: '岗  位',
                Department: '部  门',
                positionDate: '任职时间',
                Education: '教育水平',
                futurePosition: '未来职位',
                rankService: '军衔 - 军种',
                socialEdu: '社会关系及教育水平',
                Marriage: '婚 否',
                Religion: '宗教信仰',
                entranceDate: '入境日期',
                exitDate: '离境日期',
                Expired: '已过期',
                soonlyExpired: '即将过期',
                Nationality: '国  籍',
                noResultFound: '没有匹配的结果',
                IDNumberExisted: '已存在此身份证号码',
                theAccountsUsernameUnderThisIDNumberis: '在此身份证号码下的用户帐号为',
                IDNumberExistedTips: '。您可以使用该用户名及其对应密码进行登陆，点击"确定"按钮前往登陆页面，要使用另一身份证号码继续注册，请点击“取消”。',
                ThisIDNumberAlreadyTaken: '此身份证号码已被使用。',
                ThisPassportNumberAlreadyTaken: '此护照号码已被使用',
                PassportNumberExistedTips: '。您可以使用该用户名及其对应密码进行登陆，点击"确定"按钮前往登陆页面，要使用另一护照号码继续注册，请点击“取消”。',
                PassportNumberExisted: '已存在此护照号码',
                theAccountsUsernameUnderThisPassportNumberis: '在此护照号码下的用户帐号为',
                CheckingifThisIDNumberisAvailable: '检查此身份证号是否可用......',
                CheckingifThisPassportNumberisAvailable: '检查此护照号码是否可用......',
                Families: '校内家属',
                family: '家属',
                StaffBelongsto: '对应的工作人员',
                Staff: '工作人员',
                Trainee: '外籍学员',
                TraineeBelongsto: '对应的外籍学员',
                invalid: '无效数据',
                Major: '所学专业',
                College: '毕业院校',
                FamilyMembers: '家庭成员',
                familyMember: '家庭成员',
                Trainings: '受训情况',
                training: '军事训练',
                WorkingExperiences: '工作履历',
                working: '工 作',
                AbroadStudies: '留学情况',
                ContactPersons: '在中国联系人',
                contact: '联系人',
                abroadStudy: '留学经历',
                exitFlight: '回国航班号',
                entranceFlight: '来华航班号',
                Specialities: '特 长',
                ChineseName: '中文名字',
                changePassword: '修改密码',
                oldPassword: '原密码',
                newPassword: '新密码',
                PleaseInputOldPassword: '请输入原密码',
                PleaseSetANewPassword: '请设置一个新密码',
                homePhoneNumber: '本国电话',
                homeAddress: '本国地址',
                UpdateBasicProfile: '更新基础资料',
                changeBasicProfile: '修改基础资料',
                xingmingHelp: '通常是3-4个汉字',
                ChineseMobileNumber: '手机号码（中国）',
                MobileHelp: '11位数字，以1开头',
                MobileNotQualified: '手机号码格式不正确。',
                homeNumber: '国内电话（学员）',
                HomeNumberHelp: '国际电话号码',
                HomeNumberNotQualified: '不符合要求',
                HomeAddressHelp: '家庭地址（学员国内）',
                HomeAddressNotQualified: '家庭地址不能满足要求。',
                selectDepartment: '请选择所属部门',
                selectPosition: '请选择您的岗位',
                updateProfileSubmit: '提交修改',
                Close: '关 闭',
                studentId: '学 号',
                UpdatePassportVISA: '更新护照及签证信息',
                PassportType: '护照类型',
                selectPassportType: '请选择护照类型',
                VISAType: '签证类型',
                selectVISAType: '请选择签证类型',
                VISANumber: '签证编号',
                VISAValidDate: '签证有效期',
                ArriveDate: '抵达日期',
                ArriveFlightNumber: '抵达航班号',
                arriveFlightNumberNotQualified: '*抵达航班格式不正确。',
                ReturnDate: '回国日期',
                ReturnFlightNumber: '回国航班号',
                returnFlightNumberNotQualified: '*回国航班号不正确。',
                PassportVISASubmit: '提交护照签证信息',
                VISANumberNotQualified: '*签证号码不正确。',
                addFamilyMemberinCampus: '添加校内家属',
                appendFamilyinCampus: '添加校内家属',
                profileFoundTips: '已发现系统中现有数据，并为您自动填充了其它信息。',
                appendedTips: '*该家属已添加，请重新输入证件号码。',
                familyAppendSuccess: '成功添加校内家属。',
                familyAppendFailed: '添加校内家属失败，未知错误。',
                ThisIDNumberAlreadyAppended: '*此使用此身份证号码的家属已被添加。',
                checkingIfAppended: '检查此家属是否已被添加......',
                checkingIfProfileExists: '检查是否已存在该证件号码下的用户资料......',
                ThisPassportNumberAlreadyAppended: '*此护照号码下的人员已被添加为您的家属。'
            };
            languagesData['en-us'] = {
                ThisPassportNumberAlreadyAppended: '*The person with this Passport Number already addes as your family.',
                checkingIfProfileExists: 'Checking if profile exists under this certificate number...',
                checkingIfAppended: 'Checking if this family already been added...',
                ThisIDNumberAlreadyAppended: '*Family who has this ID number been added already.',
                familyAppendFailed: 'Append failed, unknown error.',
                familyAppendSuccess: 'Append one family in the campus success.',
                appendedTips: '*Already appended, please change the certificate number.',
                profileFoundTips: 'Profile found already exists, and filled other form fields automatically.',
                appendFamilyinCampus: 'Add family(in the campus)',
                addFamilyMemberinCampus: 'Add family member(in the campus)',
                VISANumberNotQualified: '*Not qualified.',
                PassportVISASubmit: 'Submit Passport and VISA data',
                returnFlightNumberNotQualified: '*Not qualified.',
                ReturnFlightNumber: 'Return flight number',
                ReturnDate: 'Return date',
                arriveFlightNumberNotQualified: '*Not qualified.',
                ArriveFlightNumber: 'Arrive flight number',
                ArriveDate: 'Arrive date',
                VISAValidDate: 'VISA valid date',
                VISANumber: 'VISA number',
                selectVISAType: 'Select VISA type',
                VISAType: 'VISA type',
                selectPassportType: 'Select Passport type',
                PassportType: 'Passport type',
                UpdatePassportVISA: 'Update Passport and VISA',
                studentId: 'Student ID number',
                Close: 'Close',
                updateProfileSubmit: 'Submit changes',
                selectPosition: 'Select your position',
                selectDepartment: 'Select department',
                HomeAddressNotQualified: 'Home address not qualified.',
                HomeAddressHelp: 'Home address(in your country)',
                HomeNumberNotQualified: 'Not qualified',
                HomeNumberHelp: 'International telephone number',
                homeNumber: 'Home number(in your country)',
                MobileNotQualified: 'Not qualified.',
                MobileHelp: '11 digits, stats with 1',
                ChineseMobileNumber: 'Mobile(Chinese)',
                ChineseName: 'Chinese name',
                xingmingHelp: '3-4 Chinese charactors',
                changeBasicProfile: 'Change basic profile',
                UpdateBasicProfile: 'Update basic profile',
                homeAddress: 'Homeland address',
                homePhoneNumber: 'Homeland phone number',
                PleaseSetANewPassword: 'A new password.',
                PleaseInputOldPassword: 'The old password.',
                newPassword: 'New password',
                oldPassword: 'Old password',
                changePassword: 'Change the password',
                Specialities: 'Specialities',
                entranceFlight: 'Arrive flight number',
                exitFlight: 'Return flight number',
                abroadStudy: 'Study abroad',
                contact: 'Contact person',
                ContactPersons: 'Contact Person in China',
                AbroadStudies: 'Abroad study experiences',
                working: 'Working experience',
                WorkingExperiences: 'Working experiences',
                training: 'Training',
                Trainings: 'Military trainings',
                familyMember: 'Family member',
                FamilyMembers: 'Family members',
                College: 'College',
                Major: 'Major in',
                invalid: 'Invalid',
                TraineeBelongsto: 'Correspond trainee',
                Trainee: 'Trainee',
                Staff: 'Staff',
                StaffBelongsto: 'Correspond staff',
                family: 'Family member',
                Families: 'Families（in the campus）',
                CheckingifThisPassportNumberisAvailable: 'Checking this Passport Number whether available...',
                CheckingifThisIDNumberisAvailable: 'Checking this ID Number wheter available...',
                theAccountsUsernameUnderThisPassportNumberis: 'The username under this Passport Number is',
                PassportNumberExisted: 'Passport Number already existed',
                ThisPassportNumberAlreadyTaken: 'This Passport Number has been registered.',
                ThisIDNumberAlreadyTaken: 'This ID Number has been registered.',
                theAccountsUsernameUnderThisIDNumberis: 'The username under this ID Number is',
                IDNumberExistedTips: '. You can login with that username and associated password. To Login with that username, press "Ok"， else press "Cancel" to register with another ID Number.',
                PassportNumberExistedTips: '. You can login with that username and associated password. To Login with that username, press "Ok"， else press "Cancel" to register with another Passport Number.',
                IDNumberExisted: 'ID Number already existed',
                noResultFound: 'No result found.',
                Nationality: 'Nationality',
                soonlyExpired: 'Expired soon',
                Expired: 'Expired',
                exitDate: 'Return date',
                entranceDate: 'Arrive date',
                Religion: 'Religion',
                Marriage: 'Marriage',
                socialEdu:'Social and Education',
                rankService: 'Rank - Service',
                futurePosition: 'Future position',
                Education: 'Education',
                positionDate: 'Position date',
                Department: 'Department',
                Position: 'Position',
                careerInfo: 'Career',
                Height: 'Height',
                Weight: 'Weight',
                Shoesize: 'Shoe size',
                physicalCondition: 'Physical conditions',
                passportValidDate: 'Passport valid date',
                visaValidDate: 'VISA valid date',
                visaType: 'VISA type',
                passportType: 'Passport type',
                workplace: 'workplace',
                notAdded: ' - Not added - ',
                passportVisa: 'Passport and VISA',
                last_updated: 'Last updated',
                PositionDepartment: 'Position - Department',
                mobile: 'Mobile number',
                Fullname: 'Full name',
                BasicProfile: 'Basic profile',
                BadNameFormat: 'Bad name format.',
                yourBirthday: 'Your birthday',
                selectLanguage: 'Select a lanauage',
                Birthday: 'Birthday',
                Gender: 'Gender',
                YourVisaNumber: 'VISA/Certificate number',
                visaNumber: 'VISA number',
                selectPersonCategory: 'Select your group',
                selectGender: 'Select a gender',
                PleaseSetAPassword: 'Please provide a password.',
                NoSpecialCharactors: 'Special charactors not allowed.',
                PleaseInputaLastname: 'Last name',
                PleaseInputaFirstname: 'First name',
                firstNameHelp: 'First name or given name. It should begin with upper case charactor, special charactors and digits are not allowed.',
                lastNameHelp: 'Last name or family name. It should begin with upper case charactor, special charactors and digits are not allowed.',
                firstName: 'First name',            
                lastName: 'Last name',
                NextStep: 'Next >>',
                PassportNumberNotQualified: 'Passport number not qualified',
                IdNumberNotQualified: 'ID number not qualified.',
                PassportNumberHelp: 'Only include upper case alphabets and digits, 4-9 of them.',
                IDNumberHelp: '18 digits, or 17 digits and a X as trailing end.',
                YourPassportNumber: 'Passport No.',
                YourIDNumber: 'ID number',
                passportNumber: 'Passport Number',
                IDNumber: 'ID Number',
                hidePassword: 'Hide the password',
                showPassword: 'Show the password',
                Category: 'Personnel category',
                credNotValidTips: 'This is because you logged in after a long time, now you should login again. To login again, press "Ok", else press "Cancel".',
                credNotValid: 'User credential expired',
                UpdatePassword: 'Change pasword',
                AdministratorAdded: 'Added by administrators',
                Created: 'Account created at',
                CardNumber: 'Campus Card Number',
                accountAndPassword: 'Account and password',
                PersonCategoryHelp: 'Please specify which group you belongs to.',
                UsernameHelpLogin: 'The account/username you have registered here.',
                PasswordHelpLogin: 'The password for your username.',
                PersonCategory: 'You are',
                logoutTips: 'After logged out, to check specific infomation, you need to login again. To logout, press "OK", else press "Cancel".',
                yestoLogout: 'Do you really want to logout?',
                menuLogout: 'Logout',
                loginSubmit: 'Login',
                Ok: 'Ok',
                Cancel: 'Cancel',
                languageSelect: 'Select language',
                profileMenuDropdown: 'Dropdown menu fro profile',
                ToggleMenu: 'Toggle menu',
                label: '昆山校区/Kunshan School',
                brandColor: "color: #404040",
                menuAbout: 'About',
                menuLogin: 'Login',
                menuRegister: 'Register',
                menuNews: 'News',
                menuNotices: 'Notices',
                profile: 'Profile',
                User: 'User ',
                Username: 'Username',
                PleaseInputaUsername: 'Please give a username.',
                Agreement: 'AGREEMENTS',
                UsernameHelp: 'It can be upper/lower case alphabets, digits, NO SPECIAL CHARATORS, at least 5 of them.',
                CheckingifThisUsernameisAvailable: 'Check whether it is available or not...',
                ThisUsernameisAlreadyTaken: 'It is occupied.',
                UsernameContainSpecialCharactors: 'Special charactor in it.',
                Password: 'Password',
                PasswordHelp: 'One upper/lower alphabet, digit and special charactor need, and at least 8 of them.',
                PasswordisNotQualified: 'Password not qualified.',
                Required: '*Needed',
                usernameMinlengthError: 'At least 5 charactors.',
                isOk: 'That\'s OK',
                passwordMinlengthError: 'At least 8 charactors.',
                Reset: 'Reset',
                newuserSubmit: 'Register',
                RegisteredSuccessfully: 'Registered Successfully, moving to index page.',
                RegisteredFailed: 'Registered failed, server problem.',
                serviceRequestFault: 'Service request failed.'
            };
            return JSON.stringify(languagesData[getLocale()]);
        };

    }]);